# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    repos:
        - {org: ongr-io, repo: ElasticsearchDSL}
        - {org: ongr-io, repo: ElasticsearchBundle}
        - {org: ongr-io, repo: FilterManagerBundle}
        - {org: ongr-io, repo: RouterBundle}
        - {org: ongr-io, repo: ApiBundle}
        - {org: ongr-io, repo: TranslationsBundle}
        - {org: ongr-io, repo: CurrencyExchangeBundle}
        - {org: ongr-io, repo: CookiesBundle}
        - {org: ongr-io, repo: SettingsBundle}
    commons:
        - {title: "What is ONGR", org: ongr-io, repo: global-docs, path: WhatIsONGR.md}
        - {title: "Start with Demo app", org: ongr-io, repo: demo.ongr.io, path: README.md}
        - {title: "Contributing to ONGR", org: ongr-io, repo: global-docs, path: Contributing.md}

services:
  facebook-auth:
        class: AppBundle\Security\FacebookAuthenticator
        autowire: true
        # use autowiring, OR you can specify the argument manually
        # arguments:
        #     - '@oauth2.registry'
        #     - '@doctrine.orm.entity_manager'
        #     - '@router'
#    app.example:
#        class: AppBundle\Service\ExampleService
#        arguments: ["@doctrine.orm.entity_manager"]
  AppBundle\EventListener\PostFacebookLoginListener:
        arguments: ['@doctrine.orm.default_entity_manager',
         '@KnpU\OAuth2ClientBundle\Client\Provider\FacebookClient']
        tags:
          - { name: kernel.event_listener, event: security.interactive_login, method: onFacebookGetUser }
  AppBundle\Controller\SpotifyController:
        arguments: ['@Symfony\Component\DependencyInjection\ContainerInterface',
         '@doctrine.orm.default_entity_manager']
